# Generated by Django 2.2.6 on 2020-10-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_pols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_pols.Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='title',
            field=models.CharField(help_text='Вариант ответа', max_length=4096, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(help_text='Вопрос', max_length=4096, verbose_name='Вопрос'),
        ),
    ]
