# Generated by Django 2.2.6 on 2020-10-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_pols', '0004_auto_20201031_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Опрос', max_length=4096, verbose_name='Опрос')),
                ('poll', models.ManyToManyField(to='p_pols.Question')),
            ],
        ),
    ]
