# Generated by Django 2.2.6 on 2020-10-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_pols', '0006_auto_20201031_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
        migrations.AddField(
            model_name='poll',
            name='poll',
            field=models.ManyToManyField(related_name='polls', to='p_pols.Question'),
        ),
    ]
