# Generated by Django 2.2.6 on 2020-10-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_pols', '0007_auto_20201031_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll',
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.ManyToManyField(help_text='Вопрос', related_name='polls', to='p_pols.Question', verbose_name='Вопрос'),
        ),
    ]
