# Generated by Django 2.2.6 on 2020-11-01 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('p_pols', '0008_auto_20201031_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 8, 59, 30, 727784, tzinfo=utc), help_text='Дата публикации', verbose_name='Дата публикации'),
        ),
    ]
