# Generated by Django 2.2.6 on 2020-11-02 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('p_pols', '0009_poll_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='p_pols.Poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 14, 10, 24, 937363, tzinfo=utc), help_text='Дата публикации', verbose_name='Дата публикации'),
        ),
    ]
